name: Check convention

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Cache modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build source code
        run: npm run build

      - name: Lint code
        run: npm run lint
