name: Check convention

on: ['pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Cache modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build source code
        run: CI=false npm run build

      - name: Lint code
        id: lint-code
        run: npm run lint

      - id: set_var
        run: |
          content=`cat ./eslint.log.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"

      - name: Create comment
        uses: jungwinter/comment@v1
        id: create
        if: always()
        with:
          type: create
          body: "${{fromJson(steps.set_var.outputs.packageJson).version}}"
          issue_number: '3'
          token: ${{ secrets.PROD_GITHUB_TOKEN }}
